let token=localStorage.getItem("fun_token"), me=null, socket=null, currentRoom=null, deferredInstall=null, authMode="login";
const $=id=>document.getElementById(id);
function toast(t){$("toast").textContent=t;$("toast").className="show";setTimeout(()=>$("toast").className="",2200)}
function show(id){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"حدث خطأ");return d}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("name").hidden=authMode==="login";$("name").required=authMode==="register"});
$("authForm").onsubmit=async e=>{e.preventDefault();try{const d=await api(authMode==="login"?"/api/login":"/api/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("email").value,password:$("password").value})});token=d.token;localStorage.setItem("fun_token",token);await boot()}catch(err){toast(err.message)}};
async function boot(){try{me=await api("/api/me");$("authView").classList.remove("active");$("nav").hidden=false;$("welcomeName").textContent=me.name;$("profileName").textContent=me.name;$("profileEmail").textContent=me.email;show("homeView");await loadHome();connect();}catch{logout()}}
async function loadHome(){const rooms=await api("/api/rooms"), anns=await api("/api/announcements");$("rooms").innerHTML=rooms.map((r,i)=>`<button class="room card" onclick="joinRoom('${r.id}','${esc(r.name)}')"><span class="emoji">${["🎙️","🎮","🎵","🔥","😂","⭐"][i%6]}</span><b>${esc(r.name)}</b><small>${esc(r.description||"غرفة ترفيهية")}</small><span class="online" id="online-${r.id}">● ${r.online||0}</span></button>`).join("");if(anns[0])$("announcement").innerHTML=`<b>${esc(anns[0].title)}</b><div>${esc(anns[0].body)}</div>`}
function connect(){socket=io();socket.on("message",m=>addMsg(m));socket.on("system",t=>addMsg({user:"النظام",text:t,time:""}));socket.on("roomOnline",x=>{const el=$("online-"+x.roomId);if(el)el.textContent="● "+x.online;if(currentRoom?.id===x.roomId)$("roomOnline").textContent=x.online+" متصل الآن"});socket.on("announcement",loadHome)}
function joinRoom(id,name){currentRoom={id,name};$("roomTitle").textContent=name;$("messages").innerHTML="";show("roomView");socket.emit("joinRoom",{roomId:id,userName:me.name})}
$("chatForm").onsubmit=e=>{e.preventDefault();const text=$("chatInput").value.trim();if(!text)return;socket.emit("message",{roomId:currentRoom.id,text});$("chatInput").value=""}
function addMsg(m){const d=document.createElement("div");d.className="msg"+(m.user===me?.name?" me":"");d.innerHTML=`<b>${esc(m.user)}</b><div>${esc(m.text)}</div><small>${esc(m.time||"")}</small>`;$("messages").appendChild(d);$("messages").scrollTop=$("messages").scrollHeight}
function startQuiz(){show("gameView");let q=[["ما هو أكبر كوكب؟","المشتري"],["كم عدد أيام الأسبوع؟","7"],["ما عاصمة مصر؟","القاهرة"]],i=0,score=0;function draw(){if(i>=q.length){$("gameBox").innerHTML=`<div><h2>🎉 انتهى التحدي</h2><p>نتيجتك: ${score}/${q.length}</p><button class="primary" onclick="show('homeView')">رجوع</button></div>`;return}const [a,b]=q[i];$("gameBox").innerHTML=`<div><h2>${a}</h2><input id="ans" placeholder="اكتب الإجابة" style="padding:13px;border-radius:12px;border:0;background:#fff;color:#111"><button class="primary" onclick="check()">إجابة</button></div>`;window.check=()=>{if($("ans").value.trim()===b)score++;i++;draw()}}draw()}
function startTap(){show("gameView");let n=0,end=Date.now()+10000;$("gameBox").innerHTML=`<div><h2>اضغط بسرعة خلال 10 ثوانٍ</h2><button class="tap" id="tap">⚡<br><small id="score">0</small></button></div>`;$("tap").onclick=()=>{$("score").textContent=++n};setTimeout(()=>{$("gameBox").innerHTML=`<div><h2>انتهى الوقت ⏱️</h2><p>نتيجتك: ${n}</p><button class="primary" onclick="show('homeView')">رجوع</button></div>`},10000)}
function scrollToRooms(){show("homeView");setTimeout(()=>$("rooms").scrollIntoView({behavior:"smooth"}),50)}
$("profileBtn").onclick=()=>show("profileView");$("menuBtn").onclick=()=>toast("استخدم الشريط السفلي للتنقل");
function logout(){localStorage.removeItem("fun_token");token=null;me=null;$("nav").hidden=true;show("authView")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();deferredInstall=null};
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");
if(token)boot();
